{% set name = "paquo" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paquo-{{ version }}.tar.gz
  sha256: f290db0c071845e880c369696a0f2f0f30e4f7d8400ae4c0a27fb47afc12f75f

build:
  noarch: python
  entry_points:
    - paquo = paquo.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - dynaconf >=3,!=3.1.0
    - jpype1 >=1.0.1
    - packaging
    - python >=3.7
    - shapely
    - typing-extensions >=4.0

test:
  imports:
    - paquo
  commands:
    - pip check
    - paquo config --help
  requires:
    - pip

about:
  home: https://github.com/bayer-science-for-a-better-life/paquo
  summary: library for interacting with QuPath
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
