{% set name = "paquo" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paquo-{{ version }}.tar.gz
  sha256: cfec4012f98f462bb8903758d426dd301ce8c409d72cae729bb2530d5167a9a4

build:
  noarch: python
  entry_points:
    - paquo = paquo.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - dynaconf >=3,!=3.1.0
    - importlib-resources  # [py<37]
    - jpype1 >=1.0.1
    - packaging
    - python
    - shapely
    - typing-extensions  # [py<38]

test:
  imports:
    - paquo
  commands:
    - pip check
    - paquo config --help
  requires:
    - pip

about:
  home: https://github.com/bayer-science-for-a-better-life/paquo
  summary: library for interacting with QuPath
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
